language: c

before_install:
  - mkdir -p /tmp/build
  - mkdir -p /tmp/scratch

install:
  - ./tools/install-chibi
  - ./tools/checkout-syntax-rules
  - ./tools/checkout-test-essentials

before_script:
  - ./tools/setup-test-rig

script:
  - ./tools/run-success-tests np/lang/impl/macros/partitioning-tests
  - ./tools/run-failure-tests np/lang/impl/macros/partitioning-tests/fail-partition-toplevel
  - ./tools/run-failure-tests np/lang/impl/macros/partitioning-tests/fail-partition-terminals
  - ./tools/run-failure-tests np/lang/impl/macros/partitioning-tests/fail-partition-nonterminals

branches:
  only:
    - /^partitioning.*$/
