language: c

before_install:
  - mkdir -p /tmp/build
  - mkdir -p /tmp/scratch

install:
  - ./tools/install-chibi
  - source ~/.profile
  - ./tools/checkout-syntax-rules
  - ./tools/checkout-test-essentials

before_script:
  - ./tools/setup-test-rig

script:
  - ./tools/run-tests

env:
  - RUN_SUCCESS_TESTS=yes RUN_FAILURE_TESTS=no
  - RUN_SUCCESS_TESTS=no  RUN_FAILURE_TESTS=yes
