#!/bin/sh
set -ex

[ -z $CHIBI_FORK ]   && CHIBI_FORK=ashinn/chibi-scheme
[ -z $CHIBI_BRANCH ] && CHIBI_BRANCH=master

chibi_prefix=$HOME/chibi

mkdir $chibi_prefix
cat <<EOF >> $HOME/.profile
# Chibi Scheme paths
export PATH=$PATH:$chibi_prefix/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$chibi_prefix/lib
EOF

cd /tmp/scratch
git clone --depth 50 --branch $CHIBI_BRANCH -- https://github.com/$CHIBI_FORK chibi-scheme

cd chibi-scheme
make PREFIX=$chibi_prefix -j$(expr $(nproc) + 1)
make PREFIX=$chibi_prefix test-all

make PREFIX=$chibi_prefix install
