#!/bin/bash

cd /tmp/build

count() { echo $#; }

output-with-indent() { sed "s/^/    /" <<< "$1"; }

actual-error-message() {
    sed -e '/^\s*called from/d' \
        -e 's/^ERROR [^:]*://'  \
        -e 's/: /\n/'
}

expected-error-message() {
    grep '^; ' | sed 's/^;//'
}

error-message-diff() {
    diff --unified --ignore-all-space       \
        <(actual-error-message <<< "$1")    \
        <(expected-error-message < "$2")
}

TEST_DIRECTORY="$1"
[ -z "$TEST_DIRECTORY" ] && TEST_DIRECTORY="$PWD"

echo
echo "Running failure tests in '$TEST_DIRECTORY'"

FAIL_FILES=$(find -L "$TEST_DIRECTORY" -type f -name 'fail-*.ss' -printf '%P\n')
FAIL_TOTAL=$(count $FAIL_FILES)
FAIL_PASSED=0

for test in $FAIL_FILES
do
    if output=$(chibi-scheme "$TEST_DIRECTORY/$test" 2>&1)
    then
        echo "X $test"
        echo "  Program exited successfully"
    else
        if diff=$(error-message-diff "$output" "$TEST_DIRECTORY/$test")
        then
            echo "- $test"
            FAIL_PASSED=$(expr $FAIL_PASSED + 1)
        else
            echo "X $test"
            echo "  Program output differs from expected"
            output-with-indent "$diff"
        fi
    fi
done

echo
echo Done
echo [ $FAIL_PASSED / $FAIL_TOTAL ]

[ "$FAIL_PASSED" == "$FAIL_TOTAL" ]
