#!/bin/bash

cd /tmp/build

count() { echo $#; }

output-with-indent() { sed "s/^/    /" <<< "$1"; }

TEST_DIRECTORY="$1"
[ -z "$TEST_DIRECTORY" ] && TEST_DIRECTORY="$PWD"

echo
echo "Running success tests in '$TEST_DIRECTORY'"

TEST_FILES=$(find -L "$TEST_DIRECTORY" -type f -name 'test-*.ss' -printf '%P\n')
TEST_TOTAL=$(count $TEST_FILES)
TEST_PASSED=0

for test in $TEST_FILES
do
    if output=$(chibi-scheme "$TEST_DIRECTORY/$test" 2>&1)
    then
        echo "- $test"
        TEST_PASSED=$(expr $TEST_PASSED + 1)
    else
        echo "X $test"
        output-with-indent "$output"
    fi
done

echo
echo "Done"
echo "[ $TEST_PASSED / $TEST_TOTAL ]"

[ "$TEST_PASSED" == "$TEST_TOTAL" ]
