#!/bin/sh
set -e

count() { echo $#; }

output_with_indent() { echo "$1" | sed "s/^/    /"; }

test_dirs=$(find . -type d -name 'test')
cd /tmp/build

test_total=0
test_passed=0

for test_dir in $test_dirs
do
    echo
    echo "Running tests in '$test_dir'"

    test_files=$(find -L "$test_dir" -type f -name 'test-*.ss' -printf '%P\n')
    test_subtotal=$(count $test_files)
    test_subpassed=0

    for test in $test_files
    do
        if output=$(chibi-scheme "$test_dir/$test" 2>&1)
        then
            echo "- $test"
            test_subpassed=$(expr $test_subpassed + 1)
        else
            echo "X $test"
            output_with_indent "$output"
        fi
    done

    echo
    echo "Done"
    echo "[ $test_subpassed / $test_subtotal ]"

    test_total=$(expr $test_total + $test_subtotal)
    test_passed=$(expr $test_passed + $test_subpassed)
done

echo
echo "All done"
echo "[ $test_passed / $test_total ]"

[ "$test_passed" = "$test_total" ]
